name: Dev Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Deploy application
      run: |
        # Запускаем полный деплой через наш готовый скрипт
        chmod +x ./deploy.sh
        ./deploy.sh
        
    - name: Verify deployment
      run: |
        # Проверяем статус через deploy.sh
        ./deploy.sh status
        
    - name: Cleanup old logs
      run: |
        # Оставляем только последние 10 файлов логов
        find . -name "*.log" -type f -mtime +7 -delete || true
        
    - name: Send notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🚀 Deployment to dev completed successfully"
        else
          echo "❌ Deployment to dev failed"
        fi

